// Fonte única do catálogo e dos favoritos. Resumos próprios; referências por espécie.
// Conservação global conferida em 07/10/2026; pode diferir de listas regionais.
// EW não é EX: projetos de reintrodução não alteram automaticamente a avaliação.
const CATEGORIAS_CONSERVACAO = {
    "EX": "Extinta",
    "EW": "Extinta na natureza",
    "CR": "Criticamente em perigo",
    "EN": "Em perigo",
    "VU": "Vulnerável",
    "NT": "Quase ameaçada",
    "LC": "Pouco preocupante",
    "DD": "Dados insuficientes",
    "NE": "Não avaliada"
};

const ESPECIES_CATALOGO = [
    {
        "id": "tucano-toco",
        "nomePopular": "Tucano-toco",
        "nomeCientifico": "Ramphastos toco",
        "audioDisponivel": true,
        "audioUrl": "Audio de passaros/Canto_Tucano_Toco.mp3",
        "fotoLocal": "foto de passaros/tucano_toco.jpg",
        "ocorrencia": "Brasil, Bolívia, Paraguai e Argentina, sobretudo no interior sul-americano.",
        "habitat": "Cerrado, matas de galeria, capões e paisagens abertas com árvores.",
        "caracteristicas": "Tem bico grande alaranjado com ponta escura e plumagem predominantemente preta, com garganta branca. Pode viver em pares ou pequenos bandos.",
        "fonteUrl": "https://www.wikiaves.com.br/wiki/tucanucu",
        "fonteConservacao": "https://www.iucnredlist.org/species/22682164/281011279",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18793",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "bem-te-vi",
        "nomePopular": "Bem-te-vi",
        "nomeCientifico": "Pitangus sulphuratus",
        "audioDisponivel": true,
        "audioUrl": "Audio de passaros/Canto_BemTevi.mp3",
        "fotoLocal": "foto de passaros/Bem_Te_Vi.jpg",
        "ocorrencia": "Do sul dos Estados Unidos e México até a Argentina, incluindo o Brasil.",
        "habitat": "Bordas de mata, ambientes aquáticos e áreas urbanas arborizadas.",
        "caracteristicas": "A barriga amarela e as faixas claras e escuras da cabeça ajudam na identificação. Seu chamado forte lembra o nome popular e costuma ser emitido de poleiros expostos.",
        "fonteUrl": "https://www.wikiaves.com.br/wiki/bem-te-vi",
        "fonteConservacao": "https://www.iucnredlist.org/species/22700605/132069895",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/16956",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "calopsita",
        "nomePopular": "Calopsita",
        "nomeCientifico": "Nymphicus hollandicus",
        "audioDisponivel": true,
        "audioUrl": "Audio de passaros/Calopsitas Cantando.mp3",
        "fotoLocal": "foto de passaros/prikito.jpg",
        "ocorrencia": "Nativa da Austrália continental; criada como ave doméstica em outros países.",
        "habitat": "Áreas abertas, savanas e bosques próximos a fontes de água.",
        "caracteristicas": "É uma pequena cacatua de cauda longa e pontuda, com crista móvel na cabeça. Vive em bandos e se alimenta principalmente de sementes.",
        "fonteUrl": "https://animaldiversity.org/accounts/Nymphicus_hollandicus/",
        "fonteConservacao": "https://www.iucnredlist.org/species/22684828/132056250",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/116993",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "cacatua",
        "nomePopular": "Cacatua",
        "nomeCientifico": "Cacatua galerita",
        "audioDisponivel": true,
        "audioUrl": "Audio de passaros/Canto_Cacatua.mp3",
        "fotoLocal": "foto de passaros/cacatua.jpg",
        "ocorrencia": "Principalmente norte e leste da Austrália; também há populações introduzidas.",
        "habitat": "Florestas, savanas arborizadas, parques e jardins.",
        "caracteristicas": "A plumagem branca contrasta com a crista amarela, que pode ser levantada. É uma ave social e de vocalização forte.",
        "fonteUrl": "https://animaldiversity.org/accounts/Cacatua_galerita/",
        "fonteConservacao": "https://www.iucnredlist.org/species/22684781/131914971",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/116834",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "papagaio",
        "nomePopular": "Papagaio",
        "nomeCientifico": "Amazona aestiva",
        "audioDisponivel": true,
        "audioUrl": "Audio de passaros/Canto_Papagaio.mp3",
        "fotoLocal": "foto de passaros/bicos-de-passaros.jpg",
        "ocorrencia": "Interior do Brasil, leste da Bolívia, Paraguai e norte da Argentina.",
        "habitat": "Florestas, savanas, matas de galeria e áreas cultivadas com árvores.",
        "caracteristicas": "Predomina o verde, com azul na fronte e amarelo na cabeça. Vive em pares ou bandos e utiliza cavidades de árvores para nidificar.",
        "fonteUrl": "https://www.wikiaves.com.br/wiki/papagaio-verdadeiro",
        "fonteConservacao": "https://www.iucnredlist.org/species/22686332/154573813",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18978",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "NT",
        "statusConservacaoNome": "Quase ameaçada",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "maritaca",
        "nomePopular": "Maritaca",
        "nomeCientifico": "Pionus maximiliani",
        "audioDisponivel": true,
        "audioUrl": "Audio de passaros/Canto_Maritaca.mp3",
        "fotoLocal": "foto de passaros/maritaca.jpg",
        "ocorrencia": "Brasil, Bolívia, Paraguai e norte da Argentina.",
        "habitat": "Florestas, matas de galeria, savanas e áreas cultivadas.",
        "caracteristicas": "Tem corpo verde, cabeça acinzentada e penas vermelhas sob a cauda. Geralmente se desloca em bandos.",
        "fonteUrl": "https://www.wikiaves.com.br/wiki/maitaca-verde",
        "fonteConservacao": "https://www.iucnredlist.org/species/22686181/263711673",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/19094",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "sabia-laranjeira",
        "nomePopular": "Sabiá-laranjeira",
        "nomeCientifico": "Turdus rufiventris",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/sabia-laranjeira",
        "ocorrencia": "Do Maranhão ao Rio Grande do Sul; também Bolívia, Paraguai, Argentina e Uruguai.",
        "habitat": "Bordas de florestas, parques, quintais e áreas urbanas arborizadas.",
        "caracteristicas": "O ventre alaranjado contrasta com o dorso mais escuro. Procura alimento no chão e possui canto melodioso, especialmente na época reprodutiva.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22708882/263937380",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/12738",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "sabia-barranco",
        "nomePopular": "Sabiá-barranco",
        "nomeCientifico": "Turdus leucomelas",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/sabia-barranco",
        "ocorrencia": "Amplamente distribuído pelo Brasil.",
        "habitat": "Matas ciliares, matas secas, cerradões, pomares e jardins.",
        "caracteristicas": "Tem dorso pardo e partes inferiores claras, com garganta estriada. Adapta-se a áreas arborizadas modificadas pelas pessoas.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22708888/132077787",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/12737",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "sabia-poca",
        "nomePopular": "Sabiá-poca",
        "nomeCientifico": "Turdus amaurochalinus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/sabia-poca",
        "ocorrencia": "Presente em grande parte do Brasil e na Argentina.",
        "habitat": "Ambientes semiflorestais, clareiras e bordas de mata; também cidades arborizadas.",
        "caracteristicas": "Possui uma mancha escura entre o olho e o bico e garganta clara com estrias. Frequentemente movimenta a cauda na vertical enquanto vocaliza.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22708891/263935588",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/12710",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "sanhaco-cinzento",
        "nomePopular": "Sanhaço-cinzento",
        "nomeCientifico": "Thraupis sayaca",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/sanhaco-cinzento",
        "ocorrencia": "Regiões tropicais e subtropicais da América do Sul, ao sul da Amazônia e a leste dos Andes.",
        "habitat": "Matas abertas e ciliares, áreas agrícolas, jardins e parques.",
        "caracteristicas": "Tem plumagem cinzenta com tons azulados nas asas e na cauda. Costuma procurar alimento nas árvores, em pares ou pequenos grupos.",
        "fonteConservacao": "https://www.wikiaves.com.br/wiki/sanhaco-cinzento",
        "conservacaoReferencia": "Global — categoria IUCN informada pelo WikiAves",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "sanhaco-do-coqueiro",
        "nomePopular": "Sanhaço-do-coqueiro",
        "nomeCientifico": "Thraupis palmarum",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/sanhaco-do-coqueiro",
        "ocorrencia": "Todo o Brasil; também América Central e grande parte da América do Sul.",
        "habitat": "Ambientes florestados, capões de cerrado, pomares e áreas urbanas arborizadas.",
        "caracteristicas": "A plumagem tem tons esverdeados e uma faixa clara nas asas. É ativo e costuma viver em pares ou pequenos grupos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22722546/132155296",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/10297",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "saira-sete-cores",
        "nomePopular": "Saíra-sete-cores",
        "nomeCientifico": "Tangara seledon",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/saira-sete-cores",
        "ocorrencia": "Leste e sul do Brasil, sudeste do Paraguai e nordeste da Argentina.",
        "habitat": "Mata Atlântica, matas litorâneas e bordas florestais.",
        "caracteristicas": "Apresenta plumagem multicolorida, com cabeça turquesa e regiões verdes e amarelas. Procura alimento nos ramos e pode acompanhar bandos mistos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22722827/264288812",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/9557",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "pica-pau-do-campo",
        "nomePopular": "Pica-pau-do-campo",
        "nomeCientifico": "Colaptes campestris",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/pica-pau-do-campo",
        "ocorrencia": "Brasil e países vizinhos, incluindo Bolívia, Paraguai, Argentina e Uruguai.",
        "habitat": "Campos, cerrado e áreas abertas.",
        "caracteristicas": "A cabeça e o peito têm regiões amarelas, e o corpo apresenta desenhos barrados. Frequentemente procura insetos no solo.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22726441/263675546",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18262",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "pica-pau-verde-barrado",
        "nomePopular": "Pica-pau-verde-barrado",
        "nomeCientifico": "Colaptes melanochloros",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/pica-pau-verde-barrado",
        "ocorrencia": "Do norte ao sul do Brasil; também Paraguai, Argentina e Uruguai.",
        "habitat": "Matas de galeria, cerrado, caatinga, bordas florestais e cidades.",
        "caracteristicas": "Tem plumagem esverdeada com manchas escuras nas partes inferiores. A cabeça combina regiões vermelhas, pretas e claras.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22727950/263614580",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18250",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "beija-flor-tesoura",
        "nomePopular": "Beija-flor-tesoura",
        "nomeCientifico": "Eupetomena macroura",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/beija-flor-tesoura",
        "ocorrencia": "Grande parte do Brasil; também Guianas, Bolívia e Paraguai.",
        "habitat": "Áreas semiabertas, bordas de mata, parques e jardins.",
        "caracteristicas": "A cauda longa e profundamente bifurcada lembra uma tesoura. Alimenta-se em flores e pode defender seu território de outras aves.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22687094/263628596",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/6065",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "beija-flor-preto",
        "nomePopular": "Beija-flor-preto",
        "nomeCientifico": "Florisuga fusca",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/beija-flor-preto",
        "ocorrencia": "Leste e centro-oeste do Brasil, da Paraíba ao Rio Grande do Sul.",
        "habitat": "Bordas de mata, capoeiras, jardins e copas de árvores.",
        "caracteristicas": "Apresenta contraste entre plumagem escura e penas brancas da cauda. Ao abrir a cauda em leque, esse desenho fica especialmente visível.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22687100/154878243",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/6420",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "arara-caninde",
        "nomePopular": "Arara-canindé",
        "nomeCientifico": "Ara ararauna",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/arara-caninde",
        "ocorrencia": "Do Panamá a regiões da América do Sul, incluindo grande parte do Brasil.",
        "habitat": "Florestas de galeria, várzeas com palmeiras e bordas de floresta.",
        "caracteristicas": "Tem dorso azul e partes inferiores amarelas, além de cauda longa. Vive em pares ou grupos e também é observada em algumas cidades.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685539/131917270",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/19018",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "arara-vermelha",
        "nomePopular": "Arara-vermelha",
        "nomeCientifico": "Ara chloropterus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/arara-vermelha",
        "ocorrencia": "Brasil e outros países da América do Sul, com ocorrência também no Panamá.",
        "habitat": "Copas de florestas altas, matas de galeria e áreas com palmeiras.",
        "caracteristicas": "A plumagem é majoritariamente vermelha, com verde e azul nas asas. Costuma se deslocar em pares ou bandos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685566/163776409",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/19016",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "arara-azul-grande",
        "nomePopular": "Arara-azul-grande",
        "nomeCientifico": "Anodorhynchus hyacinthinus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/arara-azul",
        "ocorrencia": "Brasil, Bolívia e norte do Paraguai.",
        "habitat": "Pantanal, florestas e paisagens com palmeiras, incluindo áreas sazonalmente secas.",
        "caracteristicas": "É uma arara grande de plumagem azul, com pele amarela junto aos olhos e à base do bico. Vive em pares, famílias ou pequenos bandos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685516/202613596",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18938",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "VU",
        "statusConservacaoNome": "Vulnerável",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "periquitao",
        "nomePopular": "Periquitão",
        "nomeCientifico": "Psittacara leucophthalmus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/periquitao",
        "ocorrencia": "A leste dos Andes, da Colômbia e Venezuela ao norte da Argentina e Uruguai; grande parte do Brasil.",
        "habitat": "Florestas úmidas e de galeria, palmares e ambientes urbanos.",
        "caracteristicas": "Tem plumagem verde com algumas penas vermelhas e anel claro em torno dos olhos. Voa e dorme em grupos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685682/281020219",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/367573",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "periquito-rico",
        "nomePopular": "Periquito-rico",
        "nomeCientifico": "Brotogeris tirica",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/periquito-rico",
        "ocorrencia": "Brasil oriental, especialmente a faixa da Mata Atlântica.",
        "habitat": "Florestas, áreas abertas, parques e jardins.",
        "caracteristicas": "É um periquito pequeno e predominantemente verde, com tons amarelados nas partes inferiores. Procura alimento nas copas e é frequentemente visto em bandos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685956/263977820",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/19214",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "cardeal",
        "nomePopular": "Cardeal",
        "nomeCientifico": "Paroaria coronata",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/cardeal",
        "ocorrencia": "Argentina, Bolívia, Paraguai, Uruguai e partes do Brasil; introduzido em outras regiões.",
        "habitat": "Campos de vegetação alta, bordas de matas e arrozais.",
        "caracteristicas": "Possui cabeça e topete vermelhos, muito característicos. Os jovens apresentam topete mais amarronzado.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22721582/132144578",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/10254",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "canario-da-terra",
        "nomePopular": "Canário-da-terra",
        "nomeCientifico": "Sicalis flaveola",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/canario-da-terra",
        "ocorrencia": "Brasil e vários países sul-americanos, incluindo Bolívia, Paraguai, Uruguai e Argentina.",
        "habitat": "Campos secos, cerrado, caatinga, pastagens e jardins.",
        "caracteristicas": "A plumagem pode apresentar amarelo intenso e marcas mais escuras no dorso. Fora do período reprodutivo, costuma formar grupos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22723346/132162254",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/9864",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "tico-tico",
        "nomePopular": "Tico-tico",
        "nomeCientifico": "Zonotrichia capensis",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/tico-tico",
        "ocorrencia": "Do México ao extremo sul da América do Sul; grande parte do Brasil.",
        "habitat": "Campos, plantações, jardins e outras paisagens abertas.",
        "caracteristicas": "Tem bico cônico e desenho de faixas escuras na cabeça. Vive geralmente em pares e procura alimento no solo.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22721079/138471375",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/9183",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "joao-de-barro",
        "nomePopular": "João-de-barro",
        "nomeCientifico": "Furnarius rufus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/joao-de-barro",
        "ocorrencia": "Brasil, Argentina, Paraguai, Uruguai e Bolívia.",
        "habitat": "Campos, cerrado, pastagens, jardins e bairros arborizados.",
        "caracteristicas": "Tem plumagem castanho-avermelhada. É conhecido pelo ninho de barro em forma de forno e pelo canto em dueto do casal.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22702144/263748290",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/11275",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "quero-quero",
        "nomePopular": "Quero-quero",
        "nomeCientifico": "Vanellus chilensis",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/quero-quero",
        "ocorrencia": "América do Sul, incluindo ampla área do Brasil.",
        "habitat": "Banhados, campos, margens de rios e pastagens.",
        "caracteristicas": "Combina cinza, branco e preto, com penacho e pernas avermelhadas. Vocaliza intensamente quando percebe intrusos perto de seu território.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22694075/163620949",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/4867",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "coruja-buraqueira",
        "nomePopular": "Coruja-buraqueira",
        "nomeCientifico": "Athene cunicularia",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/coruja-buraqueira",
        "ocorrencia": "Das Américas do Norte à do Sul, incluindo o Brasil.",
        "habitat": "Campos, cerrado, pastagens, restingas e terrenos abertos urbanos.",
        "caracteristicas": "É uma coruja pequena de olhos amarelos e pernas relativamente longas. Utiliza buracos no solo e pode ser observada durante o dia.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22689353/281015958",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/19975",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "carcara",
        "nomePopular": "Carcará",
        "nomeCientifico": "Caracara plancus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/carcara",
        "ocorrencia": "Américas, da Argentina ao sul dos Estados Unidos, incluindo o Brasil.",
        "habitat": "Áreas abertas, pastagens e paisagens próximas a estradas.",
        "caracteristicas": "Possui topo da cabeça escuro e face avermelhada. Passa bastante tempo no chão e também plana usando correntes de ar.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22729784/232384538",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/4715",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "anu-preto",
        "nomePopular": "Anu-preto",
        "nomeCientifico": "Crotophaga ani",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/anu-preto",
        "ocorrencia": "Caribe e grande parte das Américas, incluindo o Brasil.",
        "habitat": "Paisagens abertas com moitas, pastagens, lavouras e jardins.",
        "caracteristicas": "Tem plumagem preta, cauda longa e bico alto e robusto. É bastante social e vive em grupos.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22684434/168903230",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/1971",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "rolinha-roxa",
        "nomePopular": "Rolinha-roxa",
        "nomeCientifico": "Columbina talpacoti",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/rolinha-roxa",
        "ocorrencia": "Áreas abertas e urbanizadas do Brasil.",
        "habitat": "Campos, cerrado, pastagens, áreas agrícolas e cidades.",
        "caracteristicas": "É uma pomba pequena; o macho é mais avermelhado e a fêmea mais parda. Ambos apresentam pontos escuros nas asas.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22690784/139730677",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/3580",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "jacuguacu",
        "nomePopular": "Jacuguaçu",
        "nomeCientifico": "Penelope obscura",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/jacuguacu",
        "ocorrencia": "Sudeste e sul do Brasil; também Uruguai, Paraguai, Argentina e Bolívia.",
        "habitat": "Matas secundárias, capoeiras, plantações e matas de galeria.",
        "caracteristicas": "É um jacu grande de plumagem escura com estrias claras no pescoço e peito. Pode viver em pequenos bandos e produzir ruído forte com as asas.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22678389/263690013",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/2060",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "seriema",
        "nomePopular": "Seriema",
        "nomeCientifico": "Cariama cristata",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/seriema",
        "ocorrencia": "Brasil, Bolívia, Paraguai, Uruguai e Argentina.",
        "habitat": "Cerrado, campos e outras paisagens abertas.",
        "caracteristicas": "Tem pernas e bico avermelhados e um topete na cabeça. É principalmente terrestre e pode dormir empoleirada em árvores.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22692205/263629033",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/14",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "papagaio-charao",
        "nomePopular": "Papagaio-charão",
        "nomeCientifico": "Amazona pretrei",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/papagaio-charao",
        "ocorrencia": "Sul do Brasil, principalmente Santa Catarina e Rio Grande do Sul.",
        "habitat": "Florestas com araucárias e capões de mata em paisagens abertas.",
        "caracteristicas": "Tem plumagem verde com máscara vermelha. Realiza deslocamentos sazonais associados à disponibilidade de pinhões.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22686251/210018258",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18987",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "VU",
        "statusConservacaoNome": "Vulnerável",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "papagaio-de-peito-roxo",
        "nomePopular": "Papagaio-de-peito-roxo",
        "nomeCientifico": "Amazona vinacea",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/papagaio-de-peito-roxo",
        "ocorrencia": "Sudeste e sul do Brasil, Paraguai e nordeste da Argentina.",
        "habitat": "Florestas, incluindo matas com araucárias, associadas a áreas campestres.",
        "caracteristicas": "Tem plumagem verde e peito de tom arroxeado. Utiliza cavidades de árvores para nidificar.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22686374/118954406",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18986",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EN",
        "statusConservacaoNome": "Em perigo",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "ararinha-azul",
        "nomePopular": "Ararinha-azul",
        "nomeCientifico": "Cyanopsitta spixii",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/ararinha-azul",
        "ocorrencia": "Distribuição histórica no nordeste do Brasil, especialmente a região de Curaçá, Bahia.",
        "habitat": "Caatinga e matas ciliares de riachos temporários com caraibeiras.",
        "caracteristicas": "Apresenta plumagem azul e cabeça de tom mais claro. A conservação envolve reprodução sob cuidados humanos e projetos de reintrodução.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685533/153022606",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/19343",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EW",
        "statusConservacaoNome": "Extinta na natureza",
        "grupo": "extinta-na-natureza",
        "dataConsulta": "2026-10-07",
        "notaConservacao": "EW é a categoria da avaliação consultada. Projetos de reintrodução não equivalem automaticamente a uma nova classificação; a espécie não está totalmente extinta."
    },
    {
        "id": "arara-azul-de-lear",
        "nomePopular": "Arara-azul-de-lear",
        "nomeCientifico": "Anodorhynchus leari",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/arara-azul-de-lear",
        "ocorrencia": "Área restrita do sertão da Bahia, Brasil.",
        "habitat": "Caatinga arbórea e paredões rochosos usados para repouso.",
        "caracteristicas": "É uma arara azul com pele amarela junto ao bico. Realiza deslocamentos entre os paredões de repouso e as áreas de alimentação.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685521/176030480",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18937",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EN",
        "statusConservacaoNome": "Em perigo",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "soldadinho-do-araripe",
        "nomePopular": "Soldadinho-do-araripe",
        "nomeCientifico": "Chiroxiphia bokermanni",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/soldadinho-do-araripe",
        "sinonimos": [
            "Antilophia bokermanni"
        ],
        "fonteTaxonomia": "https://itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1259590",
        "ocorrencia": "Chapada do Araripe, nos municípios cearenses de Barbalha, Crato e Missão Velha.",
        "habitat": "Vegetação arborizada associada a cursos de água e nascentes da Chapada do Araripe.",
        "caracteristicas": "O macho tem corpo branco, asas e cauda escuras e topete vermelho; a fêmea é verde-oliva. Sua dieta inclui pequenos frutos e artrópodes.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22728410/130774493",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/1584203",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "CR",
        "statusConservacaoNome": "Criticamente em perigo",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "mutum-de-alagoas",
        "nomePopular": "Mutum-de-alagoas",
        "nomeCientifico": "Mitu mitu",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/mutum-do-nordeste",
        "sinonimos": [
            "Pauxi mitu"
        ],
        "fonteTaxonomia": "https://www.inaturalist.org/taxa/2097",
        "termoBuscaFoto": "Pauxi mitu",
        "ocorrencia": "Distribuição histórica na Mata Atlântica de Alagoas e Pernambuco, Brasil.",
        "habitat": "Florestas densas de baixa altitude da Mata Atlântica nordestina.",
        "caracteristicas": "É uma ave terrestre grande, de plumagem negra com reflexos azulados e bico avermelhado na base. Alimenta-se de frutos e participa da dispersão de sementes.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22678486/132315266",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/2097",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EW",
        "statusConservacaoNome": "Extinta na natureza",
        "grupo": "extinta-na-natureza",
        "dataConsulta": "2026-10-07",
        "notaConservacao": "EW é a categoria da avaliação consultada. Projetos de reintrodução não equivalem automaticamente a uma nova classificação; a espécie não está totalmente extinta."
    },
    {
        "id": "jacutinga",
        "nomePopular": "Jacutinga",
        "nomeCientifico": "Pipile jacutinga",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/jacutinga",
        "sinonimos": [
            "Aburria jacutinga"
        ],
        "fonteTaxonomia": "https://itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=553813",
        "ocorrencia": "Distribuição histórica do sul da Bahia ao Rio Grande do Sul, Paraguai e nordeste da Argentina.",
        "habitat": "Florestas úmidas da Mata Atlântica, especialmente locais ricos em palmeiras.",
        "caracteristicas": "É um cracídeo grande com mancha branca na asa. O desmatamento e a caça reduziram sua ocorrência a porções de sua distribuição original.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22678429/132049346",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/2109",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EN",
        "statusConservacaoNome": "Em perigo",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "tucano-de-bico-preto",
        "nomePopular": "Tucano-de-bico-preto",
        "nomeCientifico": "Ramphastos vitellinus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/tucano-de-bico-preto",
        "ocorrencia": "Amazônia e Mata Atlântica brasileiras; também Guianas, Venezuela e Bolívia.",
        "habitat": "Copas de florestas úmidas, bordas florestais e capoeiras altas.",
        "caracteristicas": "Destaca-se pelo bico predominantemente negro. Vive em pequenos grupos e participa da dispersão de sementes.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22726222/211186796",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/18803",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "LC",
        "statusConservacaoNome": "Pouco preocupante",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "ema",
        "nomePopular": "Ema",
        "nomeCientifico": "Rhea americana",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/ema",
        "ocorrencia": "Brasil, Argentina, Bolívia, Paraguai e Uruguai.",
        "habitat": "Campos naturais, cerrado, pampas e áreas agropecuárias abertas.",
        "caracteristicas": "É uma ave grande que corre e não voa. O macho incuba os ovos e acompanha os filhotes.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22678073/219615764",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/20512",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "NT",
        "statusConservacaoNome": "Quase ameaçada",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "harpia",
        "nomePopular": "Harpia",
        "nomeCientifico": "Harpia harpyja",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.wikiaves.com.br/wiki/gaviao-real",
        "ocorrencia": "Regiões florestais das Américas, do México à Argentina; no Brasil, sobretudo Amazônia e remanescentes protegidos.",
        "habitat": "Florestas primárias densas e matas de galeria.",
        "caracteristicas": "É uma grande ave de rapina, com crista, bico curvo e garras fortes. Alimenta-se de vertebrados e nidifica em árvores altas.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22695998/197957213",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/5321",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "VU",
        "statusConservacaoNome": "Vulnerável",
        "grupo": "viva",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "dodo",
        "nomePopular": "Dodô",
        "nomeCientifico": "Raphus cucullatus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://animaldiversity.org/accounts/Raphus_cucullatus/",
        "ocorrencia": "Ilha Maurício, no oceano Índico.",
        "habitat": "Principalmente florestas da ilha Maurício.",
        "caracteristicas": "Era uma ave grande, incapaz de voar, com plumagem descrita como cinzenta. Sua aparência é conhecida por relatos, ilustrações e restos preservados.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22690059/261916273",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/2713",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EX",
        "statusConservacaoNome": "Extinta",
        "grupo": "extinta",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "pombo-passageiro",
        "nomePopular": "Pombo-passageiro",
        "nomeCientifico": "Ectopistes migratorius",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.nhm.ac.uk/discover/passenger-pigeon-how-the-worlds-most-common-bird-went-extinct.html",
        "ocorrencia": "América do Norte, principalmente sua porção oriental.",
        "habitat": "Florestas com árvores produtoras de frutos e sementes, como carvalhos e faias.",
        "caracteristicas": "Formava bandos muito numerosos e fazia grandes deslocamentos em busca de alimento. Os machos tinham cabeça azul-acinzentada e peito alaranjado.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22690733/152593137",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/3665",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EX",
        "statusConservacaoNome": "Extinta",
        "grupo": "extinta",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "arau-gigante",
        "nomePopular": "Arau-gigante",
        "nomeCientifico": "Pinguinus impennis",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://animaldiversity.org/accounts/Pinguinus_impennis/",
        "ocorrencia": "Ilhas e costas do Atlântico Norte, de Canadá e Groenlândia até Islândia e Europa setentrional.",
        "habitat": "Ilhas rochosas para reprodução e mar aberto para alimentação.",
        "caracteristicas": "Era uma ave marinha grande que não voava. Tinha dorso escuro, partes inferiores brancas e asas pequenas usadas para nadar.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22694856/205919631",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/4540",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EX",
        "statusConservacaoNome": "Extinta",
        "grupo": "extinta",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "periquito-da-carolina",
        "nomePopular": "Periquito-da-carolina",
        "nomeCientifico": "Conuropsis carolinensis",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://animaldiversity.org/accounts/Conuropsis_carolinensis/",
        "ocorrencia": "Estados Unidos, sobretudo regiões orientais e centrais.",
        "habitat": "Florestas próximas a rios e pântanos; também áreas agrícolas.",
        "caracteristicas": "Apresentava plumagem principalmente verde, com cabeça amarela e regiões alaranjadas. Vivia em grupos e utilizava cavidades de árvores.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22685776/195444267",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/19204",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EX",
        "statusConservacaoNome": "Extinta",
        "grupo": "extinta",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "moa-gigante",
        "nomePopular": "Moa-gigante-do-sul",
        "nomeCientifico": "Dinornis robustus",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.nzbirdsonline.org.nz/species/south-island-giant-moa",
        "ocorrencia": "Ilha Sul da Nova Zelândia e ilhas próximas, incluindo Stewart e D'Urville.",
        "habitat": "Florestas, vegetação arbustiva, dunas e campos subalpinos.",
        "caracteristicas": "Era uma ave terrestre grande e incapaz de voar. As fêmeas eram muito maiores que os machos, e sua dieta incluía folhas, ramos e frutos.",
        "fonteConservacao": "https://www.nzbirdsonline.org.nz/species/south-island-giant-moa",
        "conservacaoReferencia": "Extinção documentada — New Zealand Birds Online; categoria equivalente EX",
        "statusConservacao": "EX",
        "statusConservacaoNome": "Extinta",
        "grupo": "extinta",
        "dataConsulta": "2026-10-07"
    },
    {
        "id": "pato-do-labrador",
        "nomePopular": "Pato-do-labrador",
        "nomeCientifico": "Camptorhynchus labradorius",
        "audioUrl": null,
        "fotoLocal": null,
        "fonteUrl": "https://www.oiseaux.net/en/oiseaux/labrador.duck.html",
        "ocorrencia": "Costa oriental da América do Norte.",
        "habitat": "Baías arenosas e estuários no inverno; habitat reprodutivo pouco conhecido.",
        "caracteristicas": "Era um pato marinho norte-americano. As informações sobre seu habitat de reprodução permanecem limitadas; registros descrevem ambientes costeiros durante a invernada.",
        "fonteConservacao": "https://www.iucnredlist.org/species/22680418/221212367",
        "fonteConservacaoConsulta": "https://api.inaturalist.org/v1/taxa/7180",
        "conservacaoReferencia": "Global — IUCN Red List, registro consultado no iNaturalist",
        "statusConservacao": "EX",
        "statusConservacaoNome": "Extinta",
        "grupo": "extinta",
        "dataConsulta": "2026-10-07"
    }
];
